# encoding: utf-8

# Adapted from
#   <http://publications.europa.eu/code/en/en-5000500.htm>
# replacing adjectives in the from 'of the [country]' with those from
#   <http://en.wiktionary.org/wiki/Appendix:Countries_of_the_world>
# where possible. (Note: DR Congo and Congo-Brazzaville share an adjective.)
#
# ISO 3166-1 alpha-3 codes from:
#   <https://en.wikipedia.org/wiki/ISO_3166-1>
#
module MusicMapper
  COUNTRIES =
    [
     {
       :name => 'Afghanistan',
       :iso_2 => 'AF',
       :iso_3 => 'AFG',
       :adjectives => ['Afghan'],
     },
     {
       :name => 'Åland Islands',
       :iso_2 => 'AX',
       :iso_3 => 'ALA',
       :adjectives => ['of the Åland Islands'],
     },
     {
       :name => 'Albania',
       :iso_2 => 'AL',
       :iso_3 => 'ALB',
       :adjectives => ['Albanian'],
     },
     {
       :name => 'Algeria',
       :iso_2 => 'DZ',
       :iso_3 => 'DZA',
       :adjectives => ['Algerian'],
     },
     {
       :name => 'American Samoa',
       :iso_2 => 'AS',
       :iso_3 => 'ASM',
       :adjectives => ['American Samoan'],
     },
     {
       :name => 'Andorra',
       :iso_2 => 'AD',
       :iso_3 => 'AND',
       :adjectives => ['Andorran'],
     },
     {
       :name => 'Angola',
       :iso_2 => 'AO',
       :iso_3 => 'AGO',
       :adjectives => ['Angolan'],
     },
     {
       :name => 'Anguilla',
       :iso_2 => 'AI',
       :iso_3 => 'AIA',
       :adjectives => ['Anguillan'],
     },
     {
       :name => 'Antarctica',
       :iso_2 => 'AQ',
       :iso_3 => 'ATA',
       :adjectives => ['Antarctic'],
     },
     {
       :name => 'Antigua and Barbuda',
       :iso_2 => 'AG',
       :iso_3 => 'ATG',
       :adjectives => ['Antiguan', 'Barbudan', 'Barbudian'],
     },
     {
       :name => 'Argentina',
       :iso_2 => 'AR',
       :iso_3 => 'ARG',
       :adjectives => ['Argentine', ' Argentinian'],
     },
     {
       :name => 'Armenia',
       :iso_2 => 'AM',
       :iso_3 => 'ARM',
       :adjectives => ['Armenian'],
     },
     {
       :name => 'Aruba',
       :iso_2 => 'AW',
       :iso_3 => 'ABW',
       :adjectives => ['Aruban'],
     },
     {
       :name => 'Australia',
       :iso_2 => 'AU',
       :iso_3 => 'AUS',
       :adjectives => ['Australian'],
     },
     {
       :name => 'Austria',
       :iso_2 => 'AT',
       :iso_3 => 'AUT',
       :adjectives => ['Austrian'],
     },
     {
       :name => 'Azerbaijan',
       :iso_2 => 'AZ',
       :iso_3 => 'AZE',
       :adjectives => ['Azerbaijani'],
     },
     {
       :name => 'Bahamas',
       :iso_2 => 'BS',
       :iso_3 => 'BHS',
       :adjectives => ['Bahamian'],
     },
     {
       :name => 'Bahrain',
       :iso_2 => 'BH',
       :iso_3 => 'BHR',
       :adjectives => ['Bahraini'],
     },
     {
       :name => 'Bangladesh',
       :iso_2 => 'BD',
       :iso_3 => 'BGD',
       :adjectives => ['Bangladeshi'],
     },
     {
       :name => 'Barbados',
       :iso_2 => 'BB',
       :iso_3 => 'BRB',
       :adjectives => ['Barbadian'],
     },
     {
       :name => 'Belarus',
       :iso_2 => 'BY',
       :iso_3 => 'BLR',
       :adjectives => ['Belarusian'],
     },
     {
       :name => 'Belgium',
       :iso_2 => 'BE',
       :iso_3 => 'BEL',
       :adjectives => ['Belgian'],
     },
     {
       :name => 'Belize',
       :iso_2 => 'BZ',
       :iso_3 => 'BLZ',
       :adjectives => ['Belizean'],
     },
     {
       :name => 'Benin',
       :iso_2 => 'BJ',
       :iso_3 => 'BEN',
       :adjectives => ['Beninese'],
     },
     {
       :name => 'Bermuda',
       :iso_2 => 'BM',
       :iso_3 => 'BMU',
       :adjectives => ['Bermudian'],
     },
     {
       :name => 'Bhutan',
       :iso_2 => 'BT',
       :iso_3 => 'BTN',
       :adjectives => ['Bhutanese'],
     },
     {
       :name => 'Bolivia',
       :iso_2 => 'BO',
       :iso_3 => 'BOL',
       :adjectives => ['Bolivian'],
     },
     {
       :name => 'Bosnia and Herzegovina',
       :iso_2 => 'BA',
       :iso_3 => 'BIH',
       :adjectives => ['Bosnian', 'Herzegovinan'],
     },
     {
       :name => 'Botswana',
       :iso_2 => 'BW',
       :iso_3 => 'BWA',
       :adjectives => ['Botswanan'],
     },
     {
       :name => 'Bouvet Island',
       :iso_2 => 'BV',
       :iso_3 => 'BVT',
       :adjectives => ['of Bouvet Island'],
     },
     {
       :name => 'Brazil',
       :iso_2 => 'BR',
       :iso_3 => 'BRA',
       :adjectives => ['Brazilian'],
     },
     {
       :name => 'British Indian Ocean Territory',
       :iso_2 => 'IO',
       :iso_3 => 'IOT',
       :adjectives => ['of the British Indian Ocean Territory'],
     },
     {
       :name => 'Brunei',
       :iso_2 => 'BN',
       :iso_3 => 'BRN',
       :adjectives => ['Bruneian'],
     },
     {
       :name => 'Bulgaria',
       :iso_2 => 'BG',
       :iso_3 => 'BGR',
       :adjectives => ['Bulgarian'],
     },
     {
       :name => 'Burkina Faso',
       :iso_2 => 'BF',
       :iso_3 => 'BFA',
       :adjectives => ['Burkinabe'],
     },
     {
       :name => 'Myanmar',
       :iso_2 => 'MM',
       :iso_3 => 'MMR',
       :adjectives => ['Myanmarese', 'Burmese'],
     },
     {
       :name => 'Burundi',
       :iso_2 => 'BI',
       :iso_3 => 'BDI',
       :adjectives => ['Burundian'],
     },
     {
       :name => 'Cambodia',
       :iso_2 => 'KH',
       :iso_3 => 'KHM',
       :adjectives => ['Cambodian'],
     },
     {
       :name => 'Cameroon',
       :iso_2 => 'CM',
       :iso_3 => 'CMR',
       :adjectives => ['Cameroonian'],
     },
     {
       :name => 'Canada',
       :iso_2 => 'CA',
       :iso_3 => 'CAN',
       :adjectives => ['Canadian'],
     },
     {
       :name => 'Cape Verde',
       :iso_2 => 'CV',
       :iso_3 => 'CPV',
       :adjectives => ['Cape Verdean'],
     },
     {
       :name => 'Cayman Islands',
       :iso_2 => 'KY',
       :iso_3 => 'CYM',
       :adjectives => ['Caymanian'],
     },
     {
       :name => 'Central African Republic',
       :iso_2 => 'CF',
       :iso_3 => 'CAF',
       :adjectives => ['Central African'],
     },
     {
       :name => 'Chad',
       :iso_2 => 'TD',
       :iso_3 => 'TCD',
       :adjectives => ['Chadian'],
     },
     {
       :name => 'Chile',
       :iso_2 => 'CL',
       :iso_3 => 'CHL',
       :adjectives => ['Chilean'],
     },
     {
       :name => 'China',
       :iso_2 => 'CN',
       :iso_3 => 'CHN',
       :adjectives => ['Chinese'],
     },
     {
       :name => 'Christmas Island',
       :iso_2 => 'CX',
       :iso_3 => 'CXR',
       :adjectives => ['of Christmas Island'],
     },
     {
       :name => 'Cocos (Keeling) Islands',
       :iso_2 => 'CC',
       :iso_3 => 'CCK',
       :adjectives => ['Cocos'],
     },
     {
       :name => 'Colombia',
       :iso_2 => 'CO',
       :iso_3 => 'COL',
       :adjectives => ['Colombian'],
     },
     {
       :name => 'Comoros',
       :iso_2 => 'KM',
       :iso_3 => 'COM',
       :adjectives => ['Comorian'],
     },
     {
       :name => 'Congo',
       :iso_2 => 'CG',
       :iso_3 => 'COG',
       :adjectives => ['Congolese'],
     },
     {
       :name => 'Cook Islands',
       :iso_2 => 'CK',
       :iso_3 => 'COK',
       :adjectives => ['Cook Island'],
     },
     {
       :name => 'Costa Rica',
       :iso_2 => 'CR',
       :iso_3 => 'CRI',
       :adjectives => ['Costa Rican'],
     },
     {
       :name => 'Côte d’Ivoire',
       :iso_2 => 'CI',
       :iso_3 => 'CIV',
       :adjectives => ['Ivorian'],
     },
     {
       :name => 'Croatia',
       :iso_2 => 'HR',
       :iso_3 => 'HRV',
       :adjectives => ['Croatian'],
     },
     {
       :name => 'Cuba',
       :iso_2 => 'CU',
       :iso_3 => 'CUB',
       :adjectives => ['Cuban'],
     },
     {
       :name => 'Curaçao',
       :iso_2 => 'CW',
       :iso_3 => 'CUW',
       :adjectives => ['Curaçaoan'],
     },
     {
       :name => 'Cyprus',
       :iso_2 => 'CY',
       :iso_3 => 'CYP',
       :adjectives => ['Cypriot'],
     },
     {
       :name => 'Czech Republic',
       :iso_2 => 'CZ',
       :iso_3 => 'CZE',
       :adjectives => ['Czech'],
     },
     {
       :name => 'Democratic Republic of the Congo',
       :iso_2 => 'CD',
       :iso_3 => 'COD',
       :adjectives => ['Congolese'],
     },
     {
       :name => 'Denmark',
       :iso_2 => 'DK',
       :iso_3 => 'DNK',
       :adjectives => ['Danish'],
     },
     {
       :name => 'Djibouti',
       :iso_2 => 'DJ',
       :iso_3 => 'DJI',
       :adjectives => ['Djiboutian'],
     },
     {
       :name => 'Dominica',
       :iso_2 => 'DM',
       :iso_3 => 'DMA',
       :adjectives => ['Dominican'],
     },
     {
       :name => 'Dominican Republic',
       :iso_2 => 'DO',
       :iso_3 => 'DOM',
       :adjectives => ['Dominican'],
     },
     {
       :name => 'Ecuador',
       :iso_2 => 'EC',
       :iso_3 => 'ECU',
       :adjectives => ['Ecuadorian'],
     },
     {
       :name => 'Egypt',
       :iso_2 => 'EG',
       :iso_3 => 'EGY',
       :adjectives => ['Egyptian'],
     },
     {
       :name => 'El Salvador',
       :iso_2 => 'SV',
       :iso_3 => 'SLV',
       :adjectives => ['Salvadorian', ' Salvadoran'],
     },
     {
       :name => 'Equatorial Guinea',
       :iso_2 => 'GQ',
       :iso_3 => 'GNQ',
       :adjectives => ['Equatorial Guinean'],
     },
     {
       :name => 'Eritrea',
       :iso_2 => 'ER',
       :iso_3 => 'ERI',
       :adjectives => ['Eritrean'],
     },
     {
       :name => 'Estonia',
       :iso_2 => 'EE',
       :iso_3 => 'EST',
       :adjectives => ['Estonian'],
     },
     {
       :name => 'Ethiopia',
       :iso_2 => 'ET',
       :iso_3 => 'ETH',
       :adjectives => ['Ethiopian'],
     },
     {
       :name => 'Faeroe Islands',
       :iso_2 => 'FO',
       :iso_3 => 'FRO',
       :adjectives => ['Faeroese'],
     },
     {
       :name => 'Falkland Islands',
       :iso_2 => 'FK',
       :iso_3 => 'FLK',
       :adjectives => ['Falkland'],
     },
     {
       :name => 'Fiji',
       :iso_2 => 'FJ',
       :iso_3 => 'FJI',
       :adjectives => ['Fijian'],
     },
     {
       :name => 'Finland',
       :iso_2 => 'FI',
       :iso_3 => 'FIN',
       :adjectives => ['Finnish'],
     },
     {
       :name => 'Macedonia, The Former Yugoslav Republic of',
       :iso_2 => 'MK',
       :iso_3 => 'MKD',
       :adjectives => ['Macedonian'],
     },
     {
       :name => 'France',
       :iso_2 => 'FR',
       :iso_3 => 'FRA',
       :adjectives => ['French'],
     },
     {
       :name => 'French Guiana',
       :iso_2 => 'GF',
       :iso_3 => 'GUF',
       :adjectives => ['Guianese'],
     },
     {
       :name => 'French Polynesia',
       :iso_2 => 'PF',
       :iso_3 => 'PYF',
       :adjectives => ['Polynesian'],
     },
     {
       :name => 'French Southern and Antarctic Lands',
       :iso_2 => 'TF',
       :iso_3 => 'ATF',
       :adjectives => ['of the French Southern and Antarctic Lands'],
     },
     {
       :name => 'Gabon',
       :iso_2 => 'GA',
       :iso_3 => 'GAB',
       :adjectives => ['Gabonese'],
     },
     {
       :name => 'Gambia, The ',
       :iso_2 => 'GM',
       :iso_3 => 'GMB',
       :adjectives => ['Gambian'],
     },
     {
       :name => 'Georgia',
       :iso_2 => 'GE',
       :iso_3 => 'GEO',
       :adjectives => ['Georgian'],
     },
     {
       :name => 'Germany',
       :iso_2 => 'DE',
       :iso_3 => 'DEU',
       :adjectives => ['German'],
     },
     {
       :name => 'Ghana',
       :iso_2 => 'GH',
       :iso_3 => 'GHA',
       :adjectives => ['Ghanaian'],
     },
     {
       :name => 'Gibraltar',
       :iso_2 => 'GI',
       :iso_3 => 'GIB',
       :adjectives => ['Gibraltarian'],
     },
     {
       :name => 'Greece',
       :iso_2 => 'GR',
       :iso_3 => 'GRC',
       :adjectives => ['Greek'],
     },
     {
       :name => 'Greenland',
       :iso_2 => 'GL',
       :iso_3 => 'GRL',
       :adjectives => ['Greenlandic'],
     },
     {
       :name => 'Grenada',
       :iso_2 => 'GD',
       :iso_3 => 'GRD',
       :adjectives => ['Grenadian'],
     },
     {
       :name => 'Guadeloupe',
       :iso_2 => 'GP',
       :iso_3 => 'GLP',
       :adjectives => ['Guadeloupean'],
     },
     {
       :name => 'Guam',
       :iso_2 => 'GU',
       :iso_3 => 'GUM',
       :adjectives => ['Guamanian'],
     },
     {
       :name => 'Guatemala',
       :iso_2 => 'GT',
       :iso_3 => 'GTM',
       :adjectives => ['Guatemalan'],
     },
     {
       :name => 'Guernsey',
       :iso_2 => 'GG',
       :iso_3 => 'GGY',
       :adjectives => ['Guernsey'],
     },
     {
       :name => 'Guinea',
       :iso_2 => 'GN',
       :iso_3 => 'GIN',
       :adjectives => ['Guinean'],
     },
     {
       :name => 'Guinea-Bissau',
       :iso_2 => 'GW',
       :iso_3 => 'GNB',
       :adjectives => ['of Guinea-Bissau'],
     },
     {
       :name => 'Guyana',
       :iso_2 => 'GY',
       :iso_3 => 'GUY',
       :adjectives => ['Guyanese'],
     },
     {
       :name => 'Haiti',
       :iso_2 => 'HT',
       :iso_3 => 'HTI',
       :adjectives => ['Haitian'],
     },
     {
       :name => 'Heard Island and McDonald Islands',
       :iso_2 => 'HM',
       :iso_3 => 'HMD',
       :adjectives => ['of the Heard Island and McDonald Islands'],
     },
     {
       :name => 'Vatican City State',
       :iso_2 => 'VA',
       :iso_3 => 'VAT',
       :adjectives => ['Vatican'],
     },
     {
       :name => 'Honduras',
       :iso_2 => 'HN',
       :iso_3 => 'HND',
       :adjectives => ['Honduran'],
     },
     {
       :name => 'Hong Kong',
       :iso_2 => 'HK',
       :iso_3 => 'HKG',
       :adjectives => ['Hong Kong Chinese'],
     },
     {
       :name => 'Hungary',
       :iso_2 => 'HU',
       :iso_3 => 'HUN',
       :adjectives => ['Hungarian'],
     },
     {
       :name => 'Iceland',
       :iso_2 => 'IS',
       :iso_3 => 'ISL',
       :adjectives => ['Icelandic'],
     },
     {
       :name => 'India',
       :iso_2 => 'IN',
       :iso_3 => 'IND',
       :adjectives => ['Indian'],
     },
     {
       :name => 'Indonesia',
       :iso_2 => 'ID',
       :iso_3 => 'IDN',
       :adjectives => ['Indonesian'],
     },
     {
       :name => 'Iran',
       :iso_2 => 'IR',
       :iso_3 => 'IRN',
       :adjectives => ['Iranian'],
     },
     {
       :name => 'Iraq',
       :iso_2 => 'IQ',
       :iso_3 => 'IRQ',
       :adjectives => ['Iraqi'],
     },
     {
       :name => 'Ireland',
       :iso_2 => 'IE',
       :iso_3 => 'IRL',
       :adjectives => ['Irish'],
     },
     {
       :name => 'Isle of Man',
       :iso_2 => 'IM',
       :iso_3 => 'IMN',
       :adjectives => ['Manx'],
     },
     {
       :name => 'Israel',
       :iso_2 => 'IL',
       :iso_3 => 'ISR',
       :adjectives => ['Israeli'],
     },
     {
       :name => 'Italy',
       :iso_2 => 'IT',
       :iso_3 => 'ITA',
       :adjectives => ['Italian'],
     },
     {
       :name => 'Jamaica',
       :iso_2 => 'JM',
       :iso_3 => 'JAM',
       :adjectives => ['Jamaican'],
     },
     {
       :name => 'Japan',
       :iso_2 => 'JP',
       :iso_3 => 'JPN',
       :adjectives => ['Japanese'],
     },
     {
       :name => 'Jersey',
       :iso_2 => 'JE',
       :iso_3 => 'JEY',
       :adjectives => ['Jersey'],
     },
     {
       :name => 'Jordan',
       :iso_2 => 'JO',
       :iso_3 => 'JOR',
       :adjectives => ['Jordanian'],
     },
     {
       :name => 'Kazakhstan',
       :iso_2 => 'KZ',
       :iso_3 => 'KAZ',
       :adjectives => ['Kazakh'],
     },
     {
       :name => 'Kenya',
       :iso_2 => 'KE',
       :iso_3 => 'KEN',
       :adjectives => ['Kenyan'],
     },
     {
       :name => 'Kiribati',
       :iso_2 => 'KI',
       :iso_3 => 'KIR',
       :adjectives => ['Kiribatian'],
     },
     {
       :name => 'Kuwait',
       :iso_2 => 'KW',
       :iso_3 => 'KWT',
       :adjectives => ['Kuwaiti'],
     },
     {
       :name => 'Kyrgyzstan',
       :iso_2 => 'KG',
       :iso_3 => 'KGZ',
       :adjectives => ['Kyrgyz'],
     },
     {
       :name => 'Laos',
       :iso_2 => 'LA',
       :iso_3 => 'LAO',
       :adjectives => ['Lao', ' Laotian'],
     },
     {
       :name => 'Latvia',
       :iso_2 => 'LV',
       :iso_3 => 'LVA',
       :adjectives => ['Latvian'],
     },
     {
       :name => 'Lebanon',
       :iso_2 => 'LB',
       :iso_3 => 'LBN',
       :adjectives => ['Lebanese'],
     },
     {
       :name => 'Lesotho',
       :iso_2 => 'LS',
       :iso_3 => 'LSO',
       :adjectives => ['of Lesotho'],
     },
     {
       :name => 'Liberia',
       :iso_2 => 'LR',
       :iso_3 => 'LBR',
       :adjectives => ['Liberian'],
     },
     {
       :name => 'Libya',
       :iso_2 => 'LY',
       :iso_3 => 'LBY',
       :adjectives => ['Libyan'],
     },
     {
       :name => 'Liechtenstein',
       :iso_2 => 'LI',
       :iso_3 => 'LIE',
       :adjectives => ['Liechtensteiner'],
     },
     {
       :name => 'Lithuania',
       :iso_2 => 'LT',
       :iso_3 => 'LTU',
       :adjectives => ['Lithuanian'],
     },
     {
       :name => 'Luxembourg',
       :iso_2 => 'LU',
       :iso_3 => 'LUX',
       :adjectives => ['Luxembourgish'],
     },
     {
       :name => 'Macao',
       :iso_2 => 'MO',
       :iso_3 => 'MAC',
       :adjectives => ['Macanese'],
     },
     {
       :name => 'Madagascar',
       :iso_2 => 'MG',
       :iso_3 => 'MDG',
       :adjectives => ['Malagasy'],
     },
     {
       :name => 'Malawi',
       :iso_2 => 'MW',
       :iso_3 => 'MWI',
       :adjectives => ['Malawian'],
     },
     {
       :name => 'Malaysia',
       :iso_2 => 'MY',
       :iso_3 => 'MYS',
       :adjectives => ['Malaysian'],
     },
     {
       :name => 'Maldives',
       :iso_2 => 'MV',
       :iso_3 => 'MDV',
       :adjectives => ['Maldivian'],
     },
     {
       :name => 'Mali',
       :iso_2 => 'ML',
       :iso_3 => 'MLI',
       :adjectives => ['Malian'],
     },
     {
       :name => 'Malta',
       :iso_2 => 'MT',
       :iso_3 => 'MLT',
       :adjectives => ['Maltese'],
     },
     {
       :name => 'Marshall Islands',
       :iso_2 => 'MH',
       :iso_3 => 'MHL',
       :adjectives => ['Marshallese'],
     },
     {
       :name => 'Martinique',
       :iso_2 => 'MQ',
       :iso_3 => 'MTQ',
       :adjectives => ['Martinican'],
     },
     {
       :name => 'Mauritania',
       :iso_2 => 'MR',
       :iso_3 => 'MRT',
       :adjectives => ['Mauritanian'],
     },
     {
       :name => 'Mauritius',
       :iso_2 => 'MU',
       :iso_3 => 'MUS',
       :adjectives => ['Mauritian'],
     },
     {
       :name => 'Mayotte',
       :iso_2 => 'YT',
       :iso_3 => 'MYT',
       :adjectives => ['Mahoran'],
     },
     {
       :name => 'Mexico',
       :iso_2 => 'MX',
       :iso_3 => 'MEX',
       :adjectives => ['Mexican'],
     },
     {
       :name => 'Micronesia',
       :iso_2 => 'FM',
       :iso_3 => 'FSM',
       :adjectives => ['Micronesian'],
     },
     {
       :name => 'Moldova',
       :iso_2 => 'MD',
       :iso_3 => 'MDA',
       :adjectives => ['Moldovan'],
     },
     {
       :name => 'Monaco',
       :iso_2 => 'MC',
       :iso_3 => 'MCO',
       :adjectives => ['Monegasque'],
     },
     {
       :name => 'Mongolia',
       :iso_2 => 'MN',
       :iso_3 => 'MNG',
       :adjectives => ['Mongolian'],
     },
     {
       :name => 'Montenegro',
       :iso_2 => 'ME',
       :iso_3 => 'MNE',
       :adjectives => ['Montenegrin'],
     },
     {
       :name => 'Montserrat',
       :iso_2 => 'MS',
       :iso_3 => 'MSR',
       :adjectives => ['Montserratian'],
     },
     {
       :name => 'Morocco',
       :iso_2 => 'MA',
       :iso_3 => 'MAR',
       :adjectives => ['Moroccan'],
     },
     {
       :name => 'Mozambique',
       :iso_2 => 'MZ',
       :iso_3 => 'MOZ',
       :adjectives => ['Mozambican'],
     },
     {
       :name => 'Namibia',
       :iso_2 => 'NA',
       :iso_3 => 'NAM',
       :adjectives => ['Namibian'],
     },
     {
       :name => 'Nauru',
       :iso_2 => 'NR',
       :iso_3 => 'NRU',
       :adjectives => ['Nauruan'],
     },
     {
       :name => 'Nepal',
       :iso_2 => 'NP',
       :iso_3 => 'NPL',
       :adjectives => ['Nepalese'],
     },
     {
       :name => 'Netherlands',
       :iso_2 => 'NL',
       :iso_3 => 'NLD',
       :adjectives => ['Netherlands', ' Dutch'],
     },
     {
       :name => 'New Caledonia',
       :iso_2 => 'NC',
       :iso_3 => 'NCL',
       :adjectives => ['New Caledonian'],
     },
     {
       :name => 'New Zealand',
       :iso_2 => 'NZ',
       :iso_3 => 'NZL',
       :adjectives => ['New Zealand'],
     },
     {
       :name => 'Nicaragua',
       :iso_2 => 'NI',
       :iso_3 => 'NIC',
       :adjectives => ['Nicaraguan'],
     },
     {
       :name => 'Niger',
       :iso_2 => 'NE',
       :iso_3 => 'NER',
       :adjectives => ['Nigerien'],
     },
     {
       :name => 'Nigeria',
       :iso_2 => 'NG',
       :iso_3 => 'NGA',
       :adjectives => ['Nigerian'],
     },
     {
       :name => 'Niue',
       :iso_2 => 'NU',
       :iso_3 => 'NIU',
       :adjectives => ['Niuean'],
     },
     {
       :name => 'Norfolk Island',
       :iso_2 => 'NF',
       :iso_3 => 'NFK',
       :adjectives => ['of Norfolk Island'],
     },
     {
       :name => 'North Korea',
       :iso_2 => 'KP',
       :iso_3 => 'PRK',
       :adjectives => ['North Korean'],
     },
     {
       :name => 'Northern Mariana Islands',
       :iso_2 => 'MP',
       :iso_3 => 'MNP',
       :adjectives => ['of the Northern Mariana Islands'],
     },
     {
       :name => 'Norway',
       :iso_2 => 'NO',
       :iso_3 => 'NOR',
       :adjectives => ['Norwegian'],
     },
     {
       :name => 'Oman',
       :iso_2 => 'OM',
       :iso_3 => 'OMN',
       :adjectives => ['Omani'],
     },
     {
       :name => 'Pakistan',
       :iso_2 => 'PK',
       :iso_3 => 'PAK',
       :adjectives => ['Pakistani'],
     },
     {
       :name => 'Palau',
       :iso_2 => 'PW',
       :iso_3 => 'PLW',
       :adjectives => ['Palauan'],
     },
     {
       :name => 'Panama',
       :iso_2 => 'PA',
       :iso_3 => 'PAN',
       :adjectives => ['Panamanian'],
     },
     {
       :name => 'Papua New Guinea',
       :iso_2 => 'PG',
       :iso_3 => 'PNG',
       :adjectives => ['Papua New Guinean'],
     },
     {
       :name => 'Paraguay',
       :iso_2 => 'PY',
       :iso_3 => 'PRY',
       :adjectives => ['Paraguayan'],
     },
     {
       :name => 'Peru',
       :iso_2 => 'PE',
       :iso_3 => 'PER',
       :adjectives => ['Peruvian'],
     },
     {
       :name => 'Philippines',
       :iso_2 => 'PH',
       :iso_3 => 'PHL',
       :adjectives => ['Philippine'],
     },
     {
       :name => 'Pitcairn Islands',
       :iso_2 => 'PN',
       :iso_3 => 'PCN',
       :adjectives => ['Pitcairner'],
     },
     {
       :name => 'Poland',
       :iso_2 => 'PL',
       :iso_3 => 'POL',
       :adjectives => ['Polish'],
     },
     {
       :name => 'Portugal',
       :iso_2 => 'PT',
       :iso_3 => 'PRT',
       :adjectives => ['Portuguese'],
     },
     {
       :name => 'Puerto Rico',
       :iso_2 => 'PR',
       :iso_3 => 'PRI',
       :adjectives => ['Puerto Rican'],
     },
     {
       :name => 'Qatar',
       :iso_2 => 'QA',
       :iso_3 => 'QAT',
       :adjectives => ['Qatari'],
     },
     {
       :name => 'Réunion',
       :iso_2 => 'RE',
       :iso_3 => 'REU',
       :adjectives => ['Reunionese'],
     },
     {
       :name => 'Romania',
       :iso_2 => 'RO',
       :iso_3 => 'ROU',
       :adjectives => ['Romanian'],
     },
     {
       :name => 'Russia',
       :iso_2 => 'RU',
       :iso_3 => 'RUS',
       :adjectives => ['Russian'],
     },
     {
       :name => 'Rwanda',
       :iso_2 => 'RW',
       :iso_3 => 'RWA',
       :adjectives => ['Rwandan', ' Rwandese'],
     },
     {
       :name => 'Saint Barthélemy',
       :iso_2 => 'BL',
       :iso_3 => 'BLM',
       :adjectives => ['of Saint Barthélemy'],
     },
     {
       :name => 'Saint Helena',
       :iso_2 => 'SH',
       :iso_3 => 'SHN',
       :adjectives => ['Saint Helenian'],
     },
     {
       :name => 'Saint Kitts and Nevis',
       :iso_2 => 'KN',
       :iso_3 => 'KNA',
       :adjectives => ['Kittsian', 'Nevisian'],
     },
     {
       :name => 'Saint Lucia',
       :iso_2 => 'LC',
       :iso_3 => 'LCA',
       :adjectives => ['Saint Lucian'],
     },
     {
       :name => 'Saint Martin',
       :iso_2 => 'MF',
       :iso_3 => 'MAF',
       :adjectives => ['of Saint Martin'],
     },
     {
       :name => 'Saint Pierre and Miquelon',
       :iso_2 => 'PM',
       :iso_3 => 'SPM',
       :adjectives => ['Saint-Pierrais', 'Miquelonnais'],
     },
     {
       :name => 'Saint Vincent and the Grenadines',
       :iso_2 => 'VC',
       :iso_3 => 'VCT',
       :adjectives => ['Vincentian', 'Grenadine'],
     },
     {
       :name => 'Samoa',
       :iso_2 => 'WS',
       :iso_3 => 'WSM',
       :adjectives => ['Samoan'],
     },
     {
       :name => 'San Marino',
       :iso_2 => 'SM',
       :iso_3 => 'SMR',
       :adjectives => ['Sanmarinese', 'San Marinese'],
     },
     {
       :name => 'São Tomé and Príncipe',
       :iso_2 => 'ST',
       :iso_3 => 'STP',
       :adjectives => ['São Toméan', 'Príncipean'],
     },
     {
       :name => 'Saudi Arabia',
       :iso_2 => 'SA',
       :iso_3 => 'SAU',
       :adjectives => ['Saudi Arabian'],
     },
     {
       :name => 'Senegal',
       :iso_2 => 'SN',
       :iso_3 => 'SEN',
       :adjectives => ['Senegalese'],
     },
     {
       :name => 'Serbia',
       :iso_2 => 'RS',
       :iso_3 => 'SRB',
       :adjectives => ['Serbian  Serbian dinar'],
     },
     {
       :name => 'Seychelles',
       :iso_2 => 'SC',
       :iso_3 => 'SYC',
       :adjectives => ['Seychellois'],
     },
     {
       :name => 'Sierra Leone',
       :iso_2 => 'SL',
       :iso_3 => 'SLE',
       :adjectives => ['Sierra Leonean'],
     },
     {
       :name => 'Singapore',
       :iso_2 => 'SG',
       :iso_3 => 'SGP',
       :adjectives => ['Singaporean'],
     },
     {
       :name => 'Sint Maarten',
       :iso_2 => 'SX',
       :iso_3 => 'SXM',
       :adjectives => ['of Sint Maarten'],
     },
     {
       :name => 'Slovakia',
       :iso_2 => 'SK',
       :iso_3 => 'SVK',
       :adjectives => ['Slovak', ' Slovakian'],
     },
     {
       :name => 'Slovenia',
       :iso_2 => 'SI',
       :iso_3 => 'SVN',
       :adjectives => ['Slovenian'],
     },
     {
       :name => 'Solomon Islands',
       :iso_2 => 'SB',
       :iso_3 => 'SLB',
       :adjectives => ['of the Solomon Islands'],
     },
     {
       :name => 'Somalia',
       :iso_2 => 'SO',
       :iso_3 => 'SOM',
       :adjectives => ['Somali', ' Somalian'],
     },
     {
       :name => 'South Africa',
       :iso_2 => 'ZA',
       :iso_3 => 'ZAF',
       :adjectives => ['South African'],
     },
     {
       :name => 'South Georgia and the South Sandwich Islands',
       :iso_2 => 'GS',
       :iso_3 => 'SGS',
       :adjectives => ['—'],
     },
     {
       :name => 'South Korea',
       :iso_2 => 'KR',
       :iso_3 => 'KOR',
       :adjectives => ['South Korean'],
     },
     {
       :name => 'South Sudan',
       :iso_2 => 'SS',
       :iso_3 => 'SSD',
       :adjectives => ['South Sudanese'],
     },
     {
       :name => 'Spain',
       :iso_2 => 'ES',
       :iso_3 => 'ESP',
       :adjectives => ['Spanish'],
     },
     {
       :name => 'Sri Lanka',
       :iso_2 => 'LK',
       :iso_3 => 'LKA',
       :adjectives => ['Sri Lankan'],
     },
     {
       :name => 'Sudan',
       :iso_2 => 'SD',
       :iso_3 => 'SDN',
       :adjectives => ['Sudanese'],
     },
     {
       :name => 'Suriname',
       :iso_2 => 'SR',
       :iso_3 => 'SUR',
       :adjectives => ['Surinamese'],
     },
     {
       :name => 'Svalbard and Jan Mayen',
       :iso_2 => 'SJ',
       :iso_3 => 'SJM',
       :adjectives => ['of Svalbard', 'of Jan Mayen'],
     },
     {
       :name => 'Swaziland',
       :iso_2 => 'SZ',
       :iso_3 => 'SWZ',
       :adjectives => ['Swazi'],
     },
     {
       :name => 'Sweden',
       :iso_2 => 'SE',
       :iso_3 => 'SWE',
       :adjectives => ['Swedish'],
     },
     {
       :name => 'Switzerland',
       :iso_2 => 'CH',
       :iso_3 => 'CHE',
       :adjectives => ['Swiss'],
     },
     {
       :name => 'Syria',
       :iso_2 => 'SY',
       :iso_3 => 'SYR',
       :adjectives => ['Syrian'],
     },
     {
       :name => 'Taiwan',
       :iso_2 => 'TW',
       :iso_3 => 'TWN',
       :adjectives => ['Taiwanese'],
     },
     {
       :name => 'Tajikistan',
       :iso_2 => 'TJ',
       :iso_3 => 'TJK',
       :adjectives => ['Tajik'],
     },
     {
       :name => 'Tanzania',
       :iso_2 => 'TZ',
       :iso_3 => 'TZA',
       :adjectives => ['Tanzanian'],
     },
     {
       :name => 'Thailand',
       :iso_2 => 'TH',
       :iso_3 => 'THA',
       :adjectives => ['Thai'],
     },
     {
       :name => 'Timor-Leste',
       :iso_2 => 'TL',
       :iso_3 => 'TLS',
       :adjectives => ['East Timorese'],
     },
     {
       :name => 'Togo',
       :iso_2 => 'TG',
       :iso_3 => 'TGO',
       :adjectives => ['Togolese'],
     },
     {
       :name => 'Tokelau',
       :iso_2 => 'TK',
       :iso_3 => 'TKL',
       :adjectives => ['Tokelauan'],
     },
     {
       :name => 'Tonga',
       :iso_2 => 'TO',
       :iso_3 => 'TON',
       :adjectives => ['Tongan'],
     },
     {
       :name => 'Trinidad and Tobago',
       :iso_2 => 'TT',
       :iso_3 => 'TTO',
       :adjectives => ['Trinidadian', 'Tobagan', 'Trinidadian and Tobagonian'],
     },
     {
       :name => 'Tunisia',
       :iso_2 => 'TN',
       :iso_3 => 'TUN',
       :adjectives => ['Tunisian'],
     },
     {
       :name => 'Turkey',
       :iso_2 => 'TR',
       :iso_3 => 'TUR',
       :adjectives => ['Turkish'],
     },
     {
       :name => 'Turkmenistan',
       :iso_2 => 'TM',
       :iso_3 => 'TKM',
       :adjectives => ['Turkmen'],
     },
     {
       :name => 'Turks and Caicos Islands',
       :iso_2 => 'TC',
       :iso_3 => 'TCA',
       :adjectives => ['of the Turks and Caicos Islands'],
     },
     {
       :name => 'Tuvalu',
       :iso_2 => 'TV',
       :iso_3 => 'TUV',
       :adjectives => ['Tuvaluan'],
     },
     {
       :name => 'Uganda',
       :iso_2 => 'UG',
       :iso_3 => 'UGA',
       :adjectives => ['Ugandan'],
     },
     {
       :name => 'Ukraine',
       :iso_2 => 'UA',
       :iso_3 => 'UKR',
       :adjectives => ['Ukrainian'],
     },
     {
       :name => 'United Arab Emirates',
       :iso_2 => 'AE',
       :iso_3 => 'ARE',
       :adjectives => ['Emirian'],
     },
     {
       :name => 'United Kingdom',
       :iso_2 => 'GB',
       :iso_3 => 'GBR',
       :adjectives => ['British', 'Scottish', 'Welsh', 'Northern Irish',
                       'English'],
     },
     {
       :name => 'United States',
       :iso_2 => 'US',
       :iso_3 => 'USA',
       :adjectives => ['American'],
     },
     {
       :name => 'United States Minor Outlying Islands',
       :iso_2 => 'UM',
       :iso_3 => 'UMI',
       :adjectives => [''],
     },
     {
       :name => 'Uruguay',
       :iso_2 => 'UY',
       :iso_3 => 'URY',
       :adjectives => ['Uruguayan'],
     },
     {
       :name => 'US Virgin Islands',
       :iso_2 => 'VI',
       :iso_3 => 'VIR',
       :adjectives => ['of the US Virgin Islands'],
     },
     {
       :name => 'Uzbekistan',
       :iso_2 => 'UZ',
       :iso_3 => 'UZB',
       :adjectives => ['Uzbek'],
     },
     {
       :name => 'Vanuatu',
       :iso_2 => 'VU',
       :iso_3 => 'VUT',
       :adjectives => ['Vanuatuan'],
     },
     {
       :name => 'Venezuela',
       :iso_2 => 'VE',
       :iso_3 => 'VEN',
       :adjectives => ['Venezuelan'],
     },
     {
       :name => 'Vietnam',
       :iso_2 => 'VN',
       :iso_3 => 'VNM',
       :adjectives => ['Vietnamese'],
     },
     {
       :name => 'Wallis and Futuna',
       :iso_2 => 'WF',
       :iso_3 => 'WLF',
       :adjectives => ['of the Wallis and Futuna Islands'],
     },
     {
       :name => 'Western Sahara',
       :iso_2 => 'EH',
       :iso_3 => 'ESH',
       :adjectives => ['Sahrawi'],
     },
     {
       :name => 'Yemen',
       :iso_2 => 'YE',
       :iso_3 => 'YEM',
       :adjectives => ['Yemeni'],
     },
     {
       :name => 'Zambia',
       :iso_2 => 'ZM',
       :iso_3 => 'ZMB',
       :adjectives => ['Zambian'],
     },
     {
       :name => 'Zimbabwe',
       :iso_2 => 'ZW',
       :iso_3 => 'ZWE',
       :adjectives => ['Zimbabwean'],
     },
    ]
end
