{-# LANGUAGE DeriveGeneric     #-}
{-# LANGUAGE OverloadedStrings #-}

module Countries (countries) where

import Data.Text
import GHC.Generics

data Country = Country
  { name :: Text
  , iso2 :: Text
  , iso3 :: Text
  , adjectives :: [Text]
  } deriving (Show, Generic)

-- Adapted from
--   <http://publications.europa.eu/code/en/en-5000500.htm>
-- replacing adjectives in the from 'of the [country]' with those from
--   <http://en.wiktionary.org/wiki/Appendix:Countries_of_the_world>
-- where possible. (Note: DR Congo and Congo-Brazzaville share an adjective.)
--
-- ISO 3166-1 alpha-3 codes from:
--   <https://en.wikipedia.org/wiki/ISO_3166-1>
--

countries =
  [ Country { name = "Afghanistan"
            , iso2 = "AF"
            , iso3 = "AFG"
            , adjectives = ["Afghan"] }
  , Country { name = "Åland Islands"
            , iso2 = "AX"
            , iso3 = "ALA"
            , adjectives = ["of the Åland Islands"] }
  , Country { name = "Albania"
            , iso2 = "AL"
            , iso3 = "ALB"
            , adjectives = ["Albanian"] }
  , Country { name = "Algeria"
            , iso2 = "DZ"
            , iso3 = "DZA"
            , adjectives = ["Algerian"] }
  , Country { name = "American Samoa"
            , iso2 = "AS"
            , iso3 = "ASM"
            , adjectives = ["American Samoan"] }
  , Country { name = "Andorra"
            , iso2 = "AD"
            , iso3 = "AND"
            , adjectives = ["Andorran"] }
  , Country { name = "Angola"
            , iso2 = "AO"
            , iso3 = "AGO"
            , adjectives = ["Angolan"] }
  , Country { name = "Anguilla"
            , iso2 = "AI"
            , iso3 = "AIA"
            , adjectives = ["Anguillan"] }
  , Country { name = "Antarctica"
            , iso2 = "AQ"
            , iso3 = "ATA"
            , adjectives = ["Antarctic"] }
  , Country { name = "Antigua and Barbuda"
            , iso2 = "AG"
            , iso3 = "ATG"
            , adjectives = ["Antiguan", "Barbudan", "Barbudian"] }
  , Country { name = "Argentina"
            , iso2 = "AR"
            , iso3 = "ARG"
            , adjectives = ["Argentine", " Argentinian"] }
  , Country { name = "Armenia"
            , iso2 = "AM"
            , iso3 = "ARM"
            , adjectives = ["Armenian"] }
  , Country { name = "Aruba"
            , iso2 = "AW"
            , iso3 = "ABW"
            , adjectives = ["Aruban"] }
  , Country { name = "Australia"
            , iso2 = "AU"
            , iso3 = "AUS"
            , adjectives = ["Australian"] }
  , Country { name = "Austria"
            , iso2 = "AT"
            , iso3 = "AUT"
            , adjectives = ["Austrian"] }
  , Country { name = "Azerbaijan"
            , iso2 = "AZ"
            , iso3 = "AZE"
            , adjectives = ["Azerbaijani"] }
  , Country { name = "Bahamas"
            , iso2 = "BS"
            , iso3 = "BHS"
            , adjectives = ["Bahamian"] }
  , Country { name = "Bahrain"
            , iso2 = "BH"
            , iso3 = "BHR"
            , adjectives = ["Bahraini"] }
  , Country { name = "Bangladesh"
            , iso2 = "BD"
            , iso3 = "BGD"
            , adjectives = ["Bangladeshi"] }
  , Country { name = "Barbados"
            , iso2 = "BB"
            , iso3 = "BRB"
            , adjectives = ["Barbadian"] }
  , Country { name = "Belarus"
            , iso2 = "BY"
            , iso3 = "BLR"
            , adjectives = ["Belarusian"] }
  , Country { name = "Belgium"
            , iso2 = "BE"
            , iso3 = "BEL"
            , adjectives = ["Belgian"] }
  , Country { name = "Belize"
            , iso2 = "BZ"
            , iso3 = "BLZ"
            , adjectives = ["Belizean"] }
  , Country { name = "Benin"
            , iso2 = "BJ"
            , iso3 = "BEN"
            , adjectives = ["Beninese"] }
  , Country { name = "Bermuda"
            , iso2 = "BM"
            , iso3 = "BMU"
            , adjectives = ["Bermudian"] }
  , Country { name = "Bhutan"
            , iso2 = "BT"
            , iso3 = "BTN"
            , adjectives = ["Bhutanese"] }
  , Country { name = "Bolivia"
            , iso2 = "BO"
            , iso3 = "BOL"
            , adjectives = ["Bolivian"] }
  , Country { name = "Bosnia and Herzegovina"
            , iso2 = "BA"
            , iso3 = "BIH"
            , adjectives = ["Bosnian", "Herzegovinan"] }
  , Country { name = "Botswana"
            , iso2 = "BW"
            , iso3 = "BWA"
            , adjectives = ["Botswanan"] }
  , Country { name = "Bouvet Island"
            , iso2 = "BV"
            , iso3 = "BVT"
            , adjectives = ["of Bouvet Island"] }
  , Country { name = "Brazil"
            , iso2 = "BR"
            , iso3 = "BRA"
            , adjectives = ["Brazilian"] }
  , Country { name = "British Indian Ocean Territory"
            , iso2 = "IO"
            , iso3 = "IOT"
            , adjectives = ["of the British Indian Ocean Territory"] }
  , Country { name = "Brunei"
            , iso2 = "BN"
            , iso3 = "BRN"
            , adjectives = ["Bruneian"] }
  , Country { name = "Bulgaria"
            , iso2 = "BG"
            , iso3 = "BGR"
            , adjectives = ["Bulgarian"] }
  , Country { name = "Burkina Faso"
            , iso2 = "BF"
            , iso3 = "BFA"
            , adjectives = ["Burkinabe"] }
  , Country { name = "Myanmar"
            , iso2 = "MM"
            , iso3 = "MMR"
            , adjectives = ["Myanmarese", "Burmese"] }
  , Country { name = "Burundi"
            , iso2 = "BI"
            , iso3 = "BDI"
            , adjectives = ["Burundian"] }
  , Country { name = "Cambodia"
            , iso2 = "KH"
            , iso3 = "KHM"
            , adjectives = ["Cambodian"] }
  , Country { name = "Cameroon"
            , iso2 = "CM"
            , iso3 = "CMR"
            , adjectives = ["Cameroonian"] }
  , Country { name = "Canada"
            , iso2 = "CA"
            , iso3 = "CAN"
            , adjectives = ["Canadian"] }
  , Country { name = "Cape Verde"
            , iso2 = "CV"
            , iso3 = "CPV"
            , adjectives = ["Cape Verdean"] }
  , Country { name = "Cayman Islands"
            , iso2 = "KY"
            , iso3 = "CYM"
            , adjectives = ["Caymanian"] }
  , Country { name = "Central African Republic"
            , iso2 = "CF"
            , iso3 = "CAF"
            , adjectives = ["Central African"] }
  , Country { name = "Chad"
            , iso2 = "TD"
            , iso3 = "TCD"
            , adjectives = ["Chadian"] }
  , Country { name = "Chile"
            , iso2 = "CL"
            , iso3 = "CHL"
            , adjectives = ["Chilean"] }
  , Country { name = "China"
            , iso2 = "CN"
            , iso3 = "CHN"
            , adjectives = ["Chinese"] }
  , Country { name = "Christmas Island"
            , iso2 = "CX"
            , iso3 = "CXR"
            , adjectives = ["of Christmas Island"] }
  , Country { name = "Cocos (Keeling) Islands"
            , iso2 = "CC"
            , iso3 = "CCK"
            , adjectives = ["Cocos"] }
  , Country { name = "Colombia"
            , iso2 = "CO"
            , iso3 = "COL"
            , adjectives = ["Colombian"] }
  , Country { name = "Comoros"
            , iso2 = "KM"
            , iso3 = "COM"
            , adjectives = ["Comorian"] }
  , Country { name = "Congo"
            , iso2 = "CG"
            , iso3 = "COG"
            , adjectives = ["Congolese"] }
  , Country { name = "Cook Islands"
            , iso2 = "CK"
            , iso3 = "COK"
            , adjectives = ["Cook Island"] }
  , Country { name = "Costa Rica"
            , iso2 = "CR"
            , iso3 = "CRI"
            , adjectives = ["Costa Rican"] }
  , Country { name = "Côte d’Ivoire"
            , iso2 = "CI"
            , iso3 = "CIV"
            , adjectives = ["Ivorian"] }
  , Country { name = "Croatia"
            , iso2 = "HR"
            , iso3 = "HRV"
            , adjectives = ["Croatian"] }
  , Country { name = "Cuba"
            , iso2 = "CU"
            , iso3 = "CUB"
            , adjectives = ["Cuban"] }
  , Country { name = "Curaçao"
            , iso2 = "CW"
            , iso3 = "CUW"
            , adjectives = ["Curaçaoan"] }
  , Country { name = "Cyprus"
            , iso2 = "CY"
            , iso3 = "CYP"
            , adjectives = ["Cypriot"] }
  , Country { name = "Czech Republic"
            , iso2 = "CZ"
            , iso3 = "CZE"
            , adjectives = ["Czech"] }
  , Country { name = "Democratic Republic of the Congo"
            , iso2 = "CD"
            , iso3 = "COD"
            , adjectives = ["Congolese"] }
  , Country { name = "Denmark"
            , iso2 = "DK"
            , iso3 = "DNK"
            , adjectives = ["Danish"] }
  , Country { name = "Djibouti"
            , iso2 = "DJ"
            , iso3 = "DJI"
            , adjectives = ["Djiboutian"] }
  , Country { name = "Dominica"
            , iso2 = "DM"
            , iso3 = "DMA"
            , adjectives = ["Dominican"] }
  , Country { name = "Dominican Republic"
            , iso2 = "DO"
            , iso3 = "DOM"
            , adjectives = ["Dominican"] }
  , Country { name = "Ecuador"
            , iso2 = "EC"
            , iso3 = "ECU"
            , adjectives = ["Ecuadorian"] }
  , Country { name = "Egypt"
            , iso2 = "EG"
            , iso3 = "EGY"
            , adjectives = ["Egyptian"] }
  , Country { name = "El Salvador"
            , iso2 = "SV"
            , iso3 = "SLV"
            , adjectives = ["Salvadorian", " Salvadoran"] }
  , Country { name = "Equatorial Guinea"
            , iso2 = "GQ"
            , iso3 = "GNQ"
            , adjectives = ["Equatorial Guinean"] }
  , Country { name = "Eritrea"
            , iso2 = "ER"
            , iso3 = "ERI"
            , adjectives = ["Eritrean"] }
  , Country { name = "Estonia"
            , iso2 = "EE"
            , iso3 = "EST"
            , adjectives = ["Estonian"] }
  , Country { name = "Ethiopia"
            , iso2 = "ET"
            , iso3 = "ETH"
            , adjectives = ["Ethiopian"] }
  , Country { name = "Faeroe Islands"
            , iso2 = "FO"
            , iso3 = "FRO"
            , adjectives = ["Faeroese"] }
  , Country { name = "Falkland Islands"
            , iso2 = "FK"
            , iso3 = "FLK"
            , adjectives = ["Falkland"] }
  , Country { name = "Fiji"
            , iso2 = "FJ"
            , iso3 = "FJI"
            , adjectives = ["Fijian"] }
  , Country { name = "Finland"
            , iso2 = "FI"
            , iso3 = "FIN"
            , adjectives = ["Finnish"] }
  , Country { name = "Macedonia, The Former Yugoslav Republic of"
            , iso2 = "MK"
            , iso3 = "MKD"
            , adjectives = ["Macedonian"] }
  , Country { name = "France"
            , iso2 = "FR"
            , iso3 = "FRA"
            , adjectives = ["French"] }
  , Country { name = "French Guiana"
            , iso2 = "GF"
            , iso3 = "GUF"
            , adjectives = ["Guianese"] }
  , Country { name = "French Polynesia"
            , iso2 = "PF"
            , iso3 = "PYF"
            , adjectives = ["Polynesian"] }
  , Country { name = "French Southern and Antarctic Lands"
            , iso2 = "TF"
            , iso3 = "ATF"
            , adjectives = ["of the French Southern and Antarctic Lands"] }
  , Country { name = "Gabon"
            , iso2 = "GA"
            , iso3 = "GAB"
            , adjectives = ["Gabonese"] }
  , Country { name = "Gambia, The "
            , iso2 = "GM"
            , iso3 = "GMB"
            , adjectives = ["Gambian"] }
  , Country { name = "Georgia"
            , iso2 = "GE"
            , iso3 = "GEO"
            , adjectives = ["Georgian"] }
  , Country { name = "Germany"
            , iso2 = "DE"
            , iso3 = "DEU"
            , adjectives = ["German"] }
  , Country { name = "Ghana"
            , iso2 = "GH"
            , iso3 = "GHA"
            , adjectives = ["Ghanaian"] }
  , Country { name = "Gibraltar"
            , iso2 = "GI"
            , iso3 = "GIB"
            , adjectives = ["Gibraltarian"] }
  , Country { name = "Greece"
            , iso2 = "GR"
            , iso3 = "GRC"
            , adjectives = ["Greek"] }
  , Country { name = "Greenland"
            , iso2 = "GL"
            , iso3 = "GRL"
            , adjectives = ["Greenlandic"] }
  , Country { name = "Grenada"
            , iso2 = "GD"
            , iso3 = "GRD"
            , adjectives = ["Grenadian"] }
  , Country { name = "Guadeloupe"
            , iso2 = "GP"
            , iso3 = "GLP"
            , adjectives = ["Guadeloupean"] }
  , Country { name = "Guam"
            , iso2 = "GU"
            , iso3 = "GUM"
            , adjectives = ["Guamanian"] }
  , Country { name = "Guatemala"
            , iso2 = "GT"
            , iso3 = "GTM"
            , adjectives = ["Guatemalan"] }
  , Country { name = "Guernsey"
            , iso2 = "GG"
            , iso3 = "GGY"
            , adjectives = ["Guernsey"] }
  , Country { name = "Guinea"
            , iso2 = "GN"
            , iso3 = "GIN"
            , adjectives = ["Guinean"] }
  , Country { name = "Guinea-Bissau"
            , iso2 = "GW"
            , iso3 = "GNB"
            , adjectives = ["of Guinea-Bissau"] }
  , Country { name = "Guyana"
            , iso2 = "GY"
            , iso3 = "GUY"
            , adjectives = ["Guyanese"] }
  , Country { name = "Haiti"
            , iso2 = "HT"
            , iso3 = "HTI"
            , adjectives = ["Haitian"] }
  , Country { name = "Heard Island and McDonald Islands"
            , iso2 = "HM"
            , iso3 = "HMD"
            , adjectives = ["of the Heard Island and McDonald Islands"] }
  , Country { name = "Vatican City State"
            , iso2 = "VA"
            , iso3 = "VAT"
            , adjectives = ["Vatican"] }
  , Country { name = "Honduras"
            , iso2 = "HN"
            , iso3 = "HND"
            , adjectives = ["Honduran"] }
  , Country { name = "Hong Kong"
            , iso2 = "HK"
            , iso3 = "HKG"
            , adjectives = ["Hong Kong Chinese"] }
  , Country { name = "Hungary"
            , iso2 = "HU"
            , iso3 = "HUN"
            , adjectives = ["Hungarian"] }
  , Country { name = "Iceland"
            , iso2 = "IS"
            , iso3 = "ISL"
            , adjectives = ["Icelandic"] }
  , Country { name = "India"
            , iso2 = "IN"
            , iso3 = "IND"
            , adjectives = ["Indian"] }
  , Country { name = "Indonesia"
            , iso2 = "ID"
            , iso3 = "IDN"
            , adjectives = ["Indonesian"] }
  , Country { name = "Iran"
            , iso2 = "IR"
            , iso3 = "IRN"
            , adjectives = ["Iranian"] }
  , Country { name = "Iraq"
            , iso2 = "IQ"
            , iso3 = "IRQ"
            , adjectives = ["Iraqi"] }
  , Country { name = "Ireland"
            , iso2 = "IE"
            , iso3 = "IRL"
            , adjectives = ["Irish"] }
  , Country { name = "Isle of Man"
            , iso2 = "IM"
            , iso3 = "IMN"
            , adjectives = ["Manx"] }
  , Country { name = "Israel"
            , iso2 = "IL"
            , iso3 = "ISR"
            , adjectives = ["Israeli"] }
  , Country { name = "Italy"
            , iso2 = "IT"
            , iso3 = "ITA"
            , adjectives = ["Italian"] }
  , Country { name = "Jamaica"
            , iso2 = "JM"
            , iso3 = "JAM"
            , adjectives = ["Jamaican"] }
  , Country { name = "Japan"
            , iso2 = "JP"
            , iso3 = "JPN"
            , adjectives = ["Japanese"] }
  , Country { name = "Jersey"
            , iso2 = "JE"
            , iso3 = "JEY"
            , adjectives = ["Jersey"] }
  , Country { name = "Jordan"
            , iso2 = "JO"
            , iso3 = "JOR"
            , adjectives = ["Jordanian"] }
  , Country { name = "Kazakhstan"
            , iso2 = "KZ"
            , iso3 = "KAZ"
            , adjectives = ["Kazakh"] }
  , Country { name = "Kenya"
            , iso2 = "KE"
            , iso3 = "KEN"
            , adjectives = ["Kenyan"] }
  , Country { name = "Kiribati"
            , iso2 = "KI"
            , iso3 = "KIR"
            , adjectives = ["Kiribatian"] }
  , Country { name = "Kuwait"
            , iso2 = "KW"
            , iso3 = "KWT"
            , adjectives = ["Kuwaiti"] }
  , Country { name = "Kyrgyzstan"
            , iso2 = "KG"
            , iso3 = "KGZ"
            , adjectives = ["Kyrgyz"] }
  , Country { name = "Laos"
            , iso2 = "LA"
            , iso3 = "LAO"
            , adjectives = ["Lao", " Laotian"] }
  , Country { name = "Latvia"
            , iso2 = "LV"
            , iso3 = "LVA"
            , adjectives = ["Latvian"] }
  , Country { name = "Lebanon"
            , iso2 = "LB"
            , iso3 = "LBN"
            , adjectives = ["Lebanese"] }
  , Country { name = "Lesotho"
            , iso2 = "LS"
            , iso3 = "LSO"
            , adjectives = ["of Lesotho"] }
  , Country { name = "Liberia"
            , iso2 = "LR"
            , iso3 = "LBR"
            , adjectives = ["Liberian"] }
  , Country { name = "Libya"
            , iso2 = "LY"
            , iso3 = "LBY"
            , adjectives = ["Libyan"] }
  , Country { name = "Liechtenstein"
            , iso2 = "LI"
            , iso3 = "LIE"
            , adjectives = ["Liechtensteiner"] }
  , Country { name = "Lithuania"
            , iso2 = "LT"
            , iso3 = "LTU"
            , adjectives = ["Lithuanian"] }
  , Country { name = "Luxembourg"
            , iso2 = "LU"
            , iso3 = "LUX"
            , adjectives = ["Luxembourgish"] }
  , Country { name = "Macao"
            , iso2 = "MO"
            , iso3 = "MAC"
            , adjectives = ["Macanese"] }
  , Country { name = "Madagascar"
            , iso2 = "MG"
            , iso3 = "MDG"
            , adjectives = ["Malagasy"] }
  , Country { name = "Malawi"
            , iso2 = "MW"
            , iso3 = "MWI"
            , adjectives = ["Malawian"] }
  , Country { name = "Malaysia"
            , iso2 = "MY"
            , iso3 = "MYS"
            , adjectives = ["Malaysian"] }
  , Country { name = "Maldives"
            , iso2 = "MV"
            , iso3 = "MDV"
            , adjectives = ["Maldivian"] }
  , Country { name = "Mali"
            , iso2 = "ML"
            , iso3 = "MLI"
            , adjectives = ["Malian"] }
  , Country { name = "Malta"
            , iso2 = "MT"
            , iso3 = "MLT"
            , adjectives = ["Maltese"] }
  , Country { name = "Marshall Islands"
            , iso2 = "MH"
            , iso3 = "MHL"
            , adjectives = ["Marshallese"] }
  , Country { name = "Martinique"
            , iso2 = "MQ"
            , iso3 = "MTQ"
            , adjectives = ["Martinican"] }
  , Country { name = "Mauritania"
            , iso2 = "MR"
            , iso3 = "MRT"
            , adjectives = ["Mauritanian"] }
  , Country { name = "Mauritius"
            , iso2 = "MU"
            , iso3 = "MUS"
            , adjectives = ["Mauritian"] }
  , Country { name = "Mayotte"
            , iso2 = "YT"
            , iso3 = "MYT"
            , adjectives = ["Mahoran"] }
  , Country { name = "Mexico"
            , iso2 = "MX"
            , iso3 = "MEX"
            , adjectives = ["Mexican"] }
  , Country { name = "Micronesia"
            , iso2 = "FM"
            , iso3 = "FSM"
            , adjectives = ["Micronesian"] }
  , Country { name = "Moldova"
            , iso2 = "MD"
            , iso3 = "MDA"
            , adjectives = ["Moldovan"] }
  , Country { name = "Monaco"
            , iso2 = "MC"
            , iso3 = "MCO"
            , adjectives = ["Monegasque"] }
  , Country { name = "Mongolia"
            , iso2 = "MN"
            , iso3 = "MNG"
            , adjectives = ["Mongolian"] }
  , Country { name = "Montenegro"
            , iso2 = "ME"
            , iso3 = "MNE"
            , adjectives = ["Montenegrin"] }
  , Country { name = "Montserrat"
            , iso2 = "MS"
            , iso3 = "MSR"
            , adjectives = ["Montserratian"] }
  , Country { name = "Morocco"
            , iso2 = "MA"
            , iso3 = "MAR"
            , adjectives = ["Moroccan"] }
  , Country { name = "Mozambique"
            , iso2 = "MZ"
            , iso3 = "MOZ"
            , adjectives = ["Mozambican"] }
  , Country { name = "Namibia"
            , iso2 = "NA"
            , iso3 = "NAM"
            , adjectives = ["Namibian"] }
  , Country { name = "Nauru"
            , iso2 = "NR"
            , iso3 = "NRU"
            , adjectives = ["Nauruan"] }
  , Country { name = "Nepal"
            , iso2 = "NP"
            , iso3 = "NPL"
            , adjectives = ["Nepalese"] }
  , Country { name = "Netherlands"
            , iso2 = "NL"
            , iso3 = "NLD"
            , adjectives = ["Netherlands", " Dutch"] }
  , Country { name = "New Caledonia"
            , iso2 = "NC"
            , iso3 = "NCL"
            , adjectives = ["New Caledonian"] }
  , Country { name = "New Zealand"
            , iso2 = "NZ"
            , iso3 = "NZL"
            , adjectives = ["New Zealand"] }
  , Country { name = "Nicaragua"
            , iso2 = "NI"
            , iso3 = "NIC"
            , adjectives = ["Nicaraguan"] }
  , Country { name = "Niger"
            , iso2 = "NE"
            , iso3 = "NER"
            , adjectives = ["Nigerien"] }
  , Country { name = "Nigeria"
            , iso2 = "NG"
            , iso3 = "NGA"
            , adjectives = ["Nigerian"] }
  , Country { name = "Niue"
            , iso2 = "NU"
            , iso3 = "NIU"
            , adjectives = ["Niuean"] }
  , Country { name = "Norfolk Island"
            , iso2 = "NF"
            , iso3 = "NFK"
            , adjectives = ["of Norfolk Island"] }
  , Country { name = "North Korea"
            , iso2 = "KP"
            , iso3 = "PRK"
            , adjectives = ["North Korean"] }
  , Country { name = "Northern Mariana Islands"
            , iso2 = "MP"
            , iso3 = "MNP"
            , adjectives = ["of the Northern Mariana Islands"] }
  , Country { name = "Norway"
            , iso2 = "NO"
            , iso3 = "NOR"
            , adjectives = ["Norwegian"] }
  , Country { name = "Oman"
            , iso2 = "OM"
            , iso3 = "OMN"
            , adjectives = ["Omani"] }
  , Country { name = "Pakistan"
            , iso2 = "PK"
            , iso3 = "PAK"
            , adjectives = ["Pakistani"] }
  , Country { name = "Palau"
            , iso2 = "PW"
            , iso3 = "PLW"
            , adjectives = ["Palauan"] }
  , Country { name = "Panama"
            , iso2 = "PA"
            , iso3 = "PAN"
            , adjectives = ["Panamanian"] }
  , Country { name = "Papua New Guinea"
            , iso2 = "PG"
            , iso3 = "PNG"
            , adjectives = ["Papua New Guinean"] }
  , Country { name = "Paraguay"
            , iso2 = "PY"
            , iso3 = "PRY"
            , adjectives = ["Paraguayan"] }
  , Country { name = "Peru"
            , iso2 = "PE"
            , iso3 = "PER"
            , adjectives = ["Peruvian"] }
  , Country { name = "Philippines"
            , iso2 = "PH"
            , iso3 = "PHL"
            , adjectives = ["Philippine"] }
  , Country { name = "Pitcairn Islands"
            , iso2 = "PN"
            , iso3 = "PCN"
            , adjectives = ["Pitcairner"] }
  , Country { name = "Poland"
            , iso2 = "PL"
            , iso3 = "POL"
            , adjectives = ["Polish"] }
  , Country { name = "Portugal"
            , iso2 = "PT"
            , iso3 = "PRT"
            , adjectives = ["Portuguese"] }
  , Country { name = "Puerto Rico"
            , iso2 = "PR"
            , iso3 = "PRI"
            , adjectives = ["Puerto Rican"] }
  , Country { name = "Qatar"
            , iso2 = "QA"
            , iso3 = "QAT"
            , adjectives = ["Qatari"] }
  , Country { name = "Réunion"
            , iso2 = "RE"
            , iso3 = "REU"
            , adjectives = ["Reunionese"] }
  , Country { name = "Romania"
            , iso2 = "RO"
            , iso3 = "ROU"
            , adjectives = ["Romanian"] }
  , Country { name = "Russia"
            , iso2 = "RU"
            , iso3 = "RUS"
            , adjectives = ["Russian"] }
  , Country { name = "Rwanda"
            , iso2 = "RW"
            , iso3 = "RWA"
            , adjectives = ["Rwandan", " Rwandese"] }
  , Country { name = "Saint Barthélemy"
            , iso2 = "BL"
            , iso3 = "BLM"
            , adjectives = ["of Saint Barthélemy"] }
  , Country { name = "Saint Helena"
            , iso2 = "SH"
            , iso3 = "SHN"
            , adjectives = ["Saint Helenian"] }
  , Country { name = "Saint Kitts and Nevis"
            , iso2 = "KN"
            , iso3 = "KNA"
            , adjectives = ["Kittsian", "Nevisian"] }
  , Country { name = "Saint Lucia"
            , iso2 = "LC"
            , iso3 = "LCA"
            , adjectives = ["Saint Lucian"] }
  , Country { name = "Saint Martin"
            , iso2 = "MF"
            , iso3 = "MAF"
            , adjectives = ["of Saint Martin"] }
  , Country { name = "Saint Pierre and Miquelon"
            , iso2 = "PM"
            , iso3 = "SPM"
            , adjectives = ["Saint-Pierrais", "Miquelonnais"] }
  , Country { name = "Saint Vincent and the Grenadines"
            , iso2 = "VC"
            , iso3 = "VCT"
            , adjectives = ["Vincentian", "Grenadine"] }
  , Country { name = "Samoa"
            , iso2 = "WS"
            , iso3 = "WSM"
            , adjectives = ["Samoan"] }
  , Country { name = "San Marino"
            , iso2 = "SM"
            , iso3 = "SMR"
            , adjectives = ["Sanmarinese", "San Marinese"] }
  , Country { name = "São Tomé and Príncipe"
            , iso2 = "ST"
            , iso3 = "STP"
            , adjectives = ["São Toméan", "Príncipean"] }
  , Country { name = "Saudi Arabia"
            , iso2 = "SA"
            , iso3 = "SAU"
            , adjectives = ["Saudi Arabian"] }
  , Country { name = "Senegal"
            , iso2 = "SN"
            , iso3 = "SEN"
            , adjectives = ["Senegalese"] }
  , Country { name = "Serbia"
            , iso2 = "RS"
            , iso3 = "SRB"
            , adjectives = ["Serbian  Serbian dinar"] }
  , Country { name = "Seychelles"
            , iso2 = "SC"
            , iso3 = "SYC"
            , adjectives = ["Seychellois"] }
  , Country { name = "Sierra Leone"
            , iso2 = "SL"
            , iso3 = "SLE"
            , adjectives = ["Sierra Leonean"] }
  , Country { name = "Singapore"
            , iso2 = "SG"
            , iso3 = "SGP"
            , adjectives = ["Singaporean"] }
  , Country { name = "Sint Maarten"
            , iso2 = "SX"
            , iso3 = "SXM"
            , adjectives = ["of Sint Maarten"] }
  , Country { name = "Slovakia"
            , iso2 = "SK"
            , iso3 = "SVK"
            , adjectives = ["Slovak", " Slovakian"] }
  , Country { name = "Slovenia"
            , iso2 = "SI"
            , iso3 = "SVN"
            , adjectives = ["Slovenian"] }
  , Country { name = "Solomon Islands"
            , iso2 = "SB"
            , iso3 = "SLB"
            , adjectives = ["of the Solomon Islands"] }
  , Country { name = "Somalia"
            , iso2 = "SO"
            , iso3 = "SOM"
            , adjectives = ["Somali", " Somalian"] }
  , Country { name = "South Africa"
            , iso2 = "ZA"
            , iso3 = "ZAF"
            , adjectives = ["South African"] }
  , Country { name = "South Georgia and the South Sandwich Islands"
            , iso2 = "GS"
            , iso3 = "SGS"
            , adjectives = ["—"] }
  , Country { name = "South Korea"
            , iso2 = "KR"
            , iso3 = "KOR"
            , adjectives = ["South Korean"] }
  , Country { name = "South Sudan"
            , iso2 = "SS"
            , iso3 = "SSD"
            , adjectives = ["South Sudanese"] }
  , Country { name = "Spain"
            , iso2 = "ES"
            , iso3 = "ESP"
            , adjectives = ["Spanish"] }
  , Country { name = "Sri Lanka"
            , iso2 = "LK"
            , iso3 = "LKA"
            , adjectives = ["Sri Lankan"] }
  , Country { name = "Sudan"
            , iso2 = "SD"
            , iso3 = "SDN"
            , adjectives = ["Sudanese"] }
  , Country { name = "Suriname"
            , iso2 = "SR"
            , iso3 = "SUR"
            , adjectives = ["Surinamese"] }
  , Country { name = "Svalbard and Jan Mayen"
            , iso2 = "SJ"
            , iso3 = "SJM"
            , adjectives = ["of Svalbard", "of Jan Mayen"] }
  , Country { name = "Swaziland"
            , iso2 = "SZ"
            , iso3 = "SWZ"
            , adjectives = ["Swazi"] }
  , Country { name = "Sweden"
            , iso2 = "SE"
            , iso3 = "SWE"
            , adjectives = ["Swedish"] }
  , Country { name = "Switzerland"
            , iso2 = "CH"
            , iso3 = "CHE"
            , adjectives = ["Swiss"] }
  , Country { name = "Syria"
            , iso2 = "SY"
            , iso3 = "SYR"
            , adjectives = ["Syrian"] }
  , Country { name = "Taiwan"
            , iso2 = "TW"
            , iso3 = "TWN"
            , adjectives = ["Taiwanese"] }
  , Country { name = "Tajikistan"
            , iso2 = "TJ"
            , iso3 = "TJK"
            , adjectives = ["Tajik"] }
  , Country { name = "Tanzania"
            , iso2 = "TZ"
            , iso3 = "TZA"
            , adjectives = ["Tanzanian"] }
  , Country { name = "Thailand"
            , iso2 = "TH"
            , iso3 = "THA"
            , adjectives = ["Thai"] }
  , Country { name = "Timor-Leste"
            , iso2 = "TL"
            , iso3 = "TLS"
            , adjectives = ["East Timorese"] }
  , Country { name = "Togo"
            , iso2 = "TG"
            , iso3 = "TGO"
            , adjectives = ["Togolese"] }
  , Country { name = "Tokelau"
            , iso2 = "TK"
            , iso3 = "TKL"
            , adjectives = ["Tokelauan"] }
  , Country { name = "Tonga"
            , iso2 = "TO"
            , iso3 = "TON"
            , adjectives = ["Tongan"] }
  , Country { name = "Trinidad and Tobago"
            , iso2 = "TT"
            , iso3 = "TTO"
            , adjectives = ["Trinidadian", "Tobagan", "Trinidadian and Tobagonian"] }
  , Country { name = "Tunisia"
            , iso2 = "TN"
            , iso3 = "TUN"
            , adjectives = ["Tunisian"] }
  , Country { name = "Turkey"
            , iso2 = "TR"
            , iso3 = "TUR"
            , adjectives = ["Turkish"] }
  , Country { name = "Turkmenistan"
            , iso2 = "TM"
            , iso3 = "TKM"
            , adjectives = ["Turkmen"] }
  , Country { name = "Turks and Caicos Islands"
            , iso2 = "TC"
            , iso3 = "TCA"
            , adjectives = ["of the Turks and Caicos Islands"] }
  , Country { name = "Tuvalu"
            , iso2 = "TV"
            , iso3 = "TUV"
            , adjectives = ["Tuvaluan"] }
  , Country { name = "Uganda"
            , iso2 = "UG"
            , iso3 = "UGA"
            , adjectives = ["Ugandan"] }
  , Country { name = "Ukraine"
            , iso2 = "UA"
            , iso3 = "UKR"
            , adjectives = ["Ukrainian"] }
  , Country { name = "United Arab Emirates"
            , iso2 = "AE"
            , iso3 = "ARE"
            , adjectives = ["Emirian"] }
  , Country { name = "United Kingdom"
            , iso2 = "GB"
            , iso3 = "GBR"
            , adjectives = ["British", "Scottish", "Welsh", "Northern Irish", "English"] }
  , Country { name = "United States"
            , iso2 = "US"
            , iso3 = "USA"
            , adjectives = ["American"] }
  , Country { name = "United States Minor Outlying Islands"
            , iso2 = "UM"
            , iso3 = "UMI"
            , adjectives = [""] }
  , Country { name = "Uruguay"
            , iso2 = "UY"
            , iso3 = "URY"
            , adjectives = ["Uruguayan"] }
  , Country { name = "US Virgin Islands"
            , iso2 = "VI"
            , iso3 = "VIR"
            , adjectives = ["of the US Virgin Islands"] }
  , Country { name = "Uzbekistan"
            , iso2 = "UZ"
            , iso3 = "UZB"
            , adjectives = ["Uzbek"] }
  , Country { name = "Vanuatu"
            , iso2 = "VU"
            , iso3 = "VUT"
            , adjectives = ["Vanuatuan"] }
  , Country { name = "Venezuela"
            , iso2 = "VE"
            , iso3 = "VEN"
            , adjectives = ["Venezuelan"] }
  , Country { name = "Vietnam"
            , iso2 = "VN"
            , iso3 = "VNM"
            , adjectives = ["Vietnamese"] }
  , Country { name = "Wallis and Futuna"
            , iso2 = "WF"
            , iso3 = "WLF"
            , adjectives = ["of the Wallis and Futuna Islands"] }
  , Country { name = "Western Sahara"
            , iso2 = "EH"
            , iso3 = "ESH"
            , adjectives = ["Sahrawi"] }
  , Country { name = "Yemen"
            , iso2 = "YE"
            , iso3 = "YEM"
            , adjectives = ["Yemeni"] }
  , Country { name = "Zambia"
            , iso2 = "ZM"
            , iso3 = "ZMB"
            , adjectives = ["Zambian"] }
  , Country { name = "Zimbabwe"
            , iso2 = "ZW"
            , iso3 = "ZWE"
            , adjectives = ["Zimbabwean"] }
  ]
