on: [push]
name: build
jobs:
  build:
    name: Build Last.fm music mapper
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: haskell/actions/setup@v2
        with:
          ghc-version: '9.2.7'
          enable-stack: true
          stack-version: 'latest'
      - name: Cache Stack
        id: cache-stack
        uses: actions/cache@v3
        with:
          path: |
            ~/.stack
            .stack-work
          key: last-fm-music-mapper-${{ hashFiles('stack.yaml') }}-${{ hashFiles('last-fm-music-mapper.cabal') }}
      - name: Setup
        run: stack --no-terminal setup
      - name: Build
        run: stack --no-terminal install
      - name: Upload
        uses: actions/upload-artifact@v3
        with:
          name: last-fm-music-mapper
          path: ~/.local/bin/last-fm-music-mapper
